#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMainForm.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Library")]
	public partial class LibraryDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAuthor(Author instance);
    partial void UpdateAuthor(Author instance);
    partial void DeleteAuthor(Author instance);
    partial void InsertBookRequest(BookRequest instance);
    partial void UpdateBookRequest(BookRequest instance);
    partial void DeleteBookRequest(BookRequest instance);
    partial void InsertBookRequestDetail(BookRequestDetail instance);
    partial void UpdateBookRequestDetail(BookRequestDetail instance);
    partial void DeleteBookRequestDetail(BookRequestDetail instance);
    partial void InsertBorrower(Borrower instance);
    partial void UpdateBorrower(Borrower instance);
    partial void DeleteBorrower(Borrower instance);
    partial void InsertBorrowerBook(BorrowerBook instance);
    partial void UpdateBorrowerBook(BorrowerBook instance);
    partial void DeleteBorrowerBook(BorrowerBook instance);
    partial void InsertCategory(Category instance);
    partial void UpdateCategory(Category instance);
    partial void DeleteCategory(Category instance);
    partial void InsertDocType(DocType instance);
    partial void UpdateDocType(DocType instance);
    partial void DeleteDocType(DocType instance);
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    partial void InsertNationality(Nationality instance);
    partial void UpdateNationality(Nationality instance);
    partial void DeleteNationality(Nationality instance);
    partial void InsertStore(Store instance);
    partial void UpdateStore(Store instance);
    partial void DeleteStore(Store instance);
    partial void InsertInvoiceMaster(InvoiceMaster instance);
    partial void UpdateInvoiceMaster(InvoiceMaster instance);
    partial void DeleteInvoiceMaster(InvoiceMaster instance);
    partial void InsertInvoiceMasterDetail(InvoiceMasterDetail instance);
    partial void UpdateInvoiceMasterDetail(InvoiceMasterDetail instance);
    partial void DeleteInvoiceMasterDetail(InvoiceMasterDetail instance);
    partial void InsertBookStore(BookStore instance);
    partial void UpdateBookStore(BookStore instance);
    partial void DeleteBookStore(BookStore instance);
    partial void InsertBook(Book instance);
    partial void UpdateBook(Book instance);
    partial void DeleteBook(Book instance);
    #endregion
		
		public LibraryDataClassesDataContext() : 
				base(global::LibraryMainForm.Properties.Settings.Default.LibraryConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LibraryDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LibraryDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LibraryDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LibraryDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Author> Authors
		{
			get
			{
				return this.GetTable<Author>();
			}
		}
		
		public System.Data.Linq.Table<BookRequest> BookRequests
		{
			get
			{
				return this.GetTable<BookRequest>();
			}
		}
		
		public System.Data.Linq.Table<BookRequestDetail> BookRequestDetails
		{
			get
			{
				return this.GetTable<BookRequestDetail>();
			}
		}
		
		public System.Data.Linq.Table<Borrower> Borrowers
		{
			get
			{
				return this.GetTable<Borrower>();
			}
		}
		
		public System.Data.Linq.Table<BorrowerBook> BorrowerBooks
		{
			get
			{
				return this.GetTable<BorrowerBook>();
			}
		}
		
		public System.Data.Linq.Table<Category> Categories
		{
			get
			{
				return this.GetTable<Category>();
			}
		}
		
		public System.Data.Linq.Table<DocType> DocTypes
		{
			get
			{
				return this.GetTable<DocType>();
			}
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
		
		public System.Data.Linq.Table<Nationality> Nationalities
		{
			get
			{
				return this.GetTable<Nationality>();
			}
		}
		
		public System.Data.Linq.Table<Store> Stores
		{
			get
			{
				return this.GetTable<Store>();
			}
		}
		
		public System.Data.Linq.Table<InvoiceMaster> InvoiceMasters
		{
			get
			{
				return this.GetTable<InvoiceMaster>();
			}
		}
		
		public System.Data.Linq.Table<InvoiceMasterDetail> InvoiceMasterDetails
		{
			get
			{
				return this.GetTable<InvoiceMasterDetail>();
			}
		}
		
		public System.Data.Linq.Table<BookStore> BookStores
		{
			get
			{
				return this.GetTable<BookStore>();
			}
		}
		
		public System.Data.Linq.Table<Book> Books
		{
			get
			{
				return this.GetTable<Book>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Author")]
	public partial class Author : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _AuthorId;
		
		private string _AuthorName;
		
		private System.Nullable<System.DateTime> _AuthorBirthdate;
		
		private System.Nullable<long> _NationalityId;
		
		private System.Nullable<System.DateTime> _AuthorDeathdate;
		
		private System.Nullable<int> _AuthorBookNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAuthorIdChanging(long value);
    partial void OnAuthorIdChanged();
    partial void OnAuthorNameChanging(string value);
    partial void OnAuthorNameChanged();
    partial void OnAuthorBirthdateChanging(System.Nullable<System.DateTime> value);
    partial void OnAuthorBirthdateChanged();
    partial void OnNationalityIdChanging(System.Nullable<long> value);
    partial void OnNationalityIdChanged();
    partial void OnAuthorDeathdateChanging(System.Nullable<System.DateTime> value);
    partial void OnAuthorDeathdateChanged();
    partial void OnAuthorBookNumberChanging(System.Nullable<int> value);
    partial void OnAuthorBookNumberChanged();
    #endregion
		
		public Author()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long AuthorId
		{
			get
			{
				return this._AuthorId;
			}
			set
			{
				if ((this._AuthorId != value))
				{
					this.OnAuthorIdChanging(value);
					this.SendPropertyChanging();
					this._AuthorId = value;
					this.SendPropertyChanged("AuthorId");
					this.OnAuthorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorName", DbType="NVarChar(MAX)")]
		public string AuthorName
		{
			get
			{
				return this._AuthorName;
			}
			set
			{
				if ((this._AuthorName != value))
				{
					this.OnAuthorNameChanging(value);
					this.SendPropertyChanging();
					this._AuthorName = value;
					this.SendPropertyChanged("AuthorName");
					this.OnAuthorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorBirthdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> AuthorBirthdate
		{
			get
			{
				return this._AuthorBirthdate;
			}
			set
			{
				if ((this._AuthorBirthdate != value))
				{
					this.OnAuthorBirthdateChanging(value);
					this.SendPropertyChanging();
					this._AuthorBirthdate = value;
					this.SendPropertyChanged("AuthorBirthdate");
					this.OnAuthorBirthdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalityId", DbType="BigInt")]
		public System.Nullable<long> NationalityId
		{
			get
			{
				return this._NationalityId;
			}
			set
			{
				if ((this._NationalityId != value))
				{
					this.OnNationalityIdChanging(value);
					this.SendPropertyChanging();
					this._NationalityId = value;
					this.SendPropertyChanged("NationalityId");
					this.OnNationalityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorDeathdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> AuthorDeathdate
		{
			get
			{
				return this._AuthorDeathdate;
			}
			set
			{
				if ((this._AuthorDeathdate != value))
				{
					this.OnAuthorDeathdateChanging(value);
					this.SendPropertyChanging();
					this._AuthorDeathdate = value;
					this.SendPropertyChanged("AuthorDeathdate");
					this.OnAuthorDeathdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorBookNumber", DbType="Int")]
		public System.Nullable<int> AuthorBookNumber
		{
			get
			{
				return this._AuthorBookNumber;
			}
			set
			{
				if ((this._AuthorBookNumber != value))
				{
					this.OnAuthorBookNumberChanging(value);
					this.SendPropertyChanging();
					this._AuthorBookNumber = value;
					this.SendPropertyChanged("AuthorBookNumber");
					this.OnAuthorBookNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BookRequest")]
	public partial class BookRequest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _BookRequestId;
		
		private System.Nullable<long> _DocTypeId;
		
		private System.Nullable<System.DateTime> _BookRequestDate;
		
		private System.Nullable<long> _TotalNumberOfBooks;
		
		private System.Nullable<bool> _IsRecieved;
		
		private System.Nullable<bool> _IsClosed;
		
		private System.Nullable<long> _EmployeeIdForTransffering;
		
		private System.Nullable<long> _EmployeeIdForRecieving;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBookRequestIdChanging(long value);
    partial void OnBookRequestIdChanged();
    partial void OnDocTypeIdChanging(System.Nullable<long> value);
    partial void OnDocTypeIdChanged();
    partial void OnBookRequestDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBookRequestDateChanged();
    partial void OnTotalNumberOfBooksChanging(System.Nullable<long> value);
    partial void OnTotalNumberOfBooksChanged();
    partial void OnIsRecievedChanging(System.Nullable<bool> value);
    partial void OnIsRecievedChanged();
    partial void OnIsClosedChanging(System.Nullable<bool> value);
    partial void OnIsClosedChanged();
    partial void OnEmployeeIdForTransfferingChanging(System.Nullable<long> value);
    partial void OnEmployeeIdForTransfferingChanged();
    partial void OnEmployeeIdForRecievingChanging(System.Nullable<long> value);
    partial void OnEmployeeIdForRecievingChanged();
    #endregion
		
		public BookRequest()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookRequestId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long BookRequestId
		{
			get
			{
				return this._BookRequestId;
			}
			set
			{
				if ((this._BookRequestId != value))
				{
					this.OnBookRequestIdChanging(value);
					this.SendPropertyChanging();
					this._BookRequestId = value;
					this.SendPropertyChanged("BookRequestId");
					this.OnBookRequestIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocTypeId", DbType="BigInt")]
		public System.Nullable<long> DocTypeId
		{
			get
			{
				return this._DocTypeId;
			}
			set
			{
				if ((this._DocTypeId != value))
				{
					this.OnDocTypeIdChanging(value);
					this.SendPropertyChanging();
					this._DocTypeId = value;
					this.SendPropertyChanged("DocTypeId");
					this.OnDocTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookRequestDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BookRequestDate
		{
			get
			{
				return this._BookRequestDate;
			}
			set
			{
				if ((this._BookRequestDate != value))
				{
					this.OnBookRequestDateChanging(value);
					this.SendPropertyChanging();
					this._BookRequestDate = value;
					this.SendPropertyChanged("BookRequestDate");
					this.OnBookRequestDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalNumberOfBooks", DbType="BigInt")]
		public System.Nullable<long> TotalNumberOfBooks
		{
			get
			{
				return this._TotalNumberOfBooks;
			}
			set
			{
				if ((this._TotalNumberOfBooks != value))
				{
					this.OnTotalNumberOfBooksChanging(value);
					this.SendPropertyChanging();
					this._TotalNumberOfBooks = value;
					this.SendPropertyChanged("TotalNumberOfBooks");
					this.OnTotalNumberOfBooksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRecieved", DbType="Bit")]
		public System.Nullable<bool> IsRecieved
		{
			get
			{
				return this._IsRecieved;
			}
			set
			{
				if ((this._IsRecieved != value))
				{
					this.OnIsRecievedChanging(value);
					this.SendPropertyChanging();
					this._IsRecieved = value;
					this.SendPropertyChanged("IsRecieved");
					this.OnIsRecievedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsClosed", DbType="Bit")]
		public System.Nullable<bool> IsClosed
		{
			get
			{
				return this._IsClosed;
			}
			set
			{
				if ((this._IsClosed != value))
				{
					this.OnIsClosedChanging(value);
					this.SendPropertyChanging();
					this._IsClosed = value;
					this.SendPropertyChanged("IsClosed");
					this.OnIsClosedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeIdForTransffering", DbType="BigInt")]
		public System.Nullable<long> EmployeeIdForTransffering
		{
			get
			{
				return this._EmployeeIdForTransffering;
			}
			set
			{
				if ((this._EmployeeIdForTransffering != value))
				{
					this.OnEmployeeIdForTransfferingChanging(value);
					this.SendPropertyChanging();
					this._EmployeeIdForTransffering = value;
					this.SendPropertyChanged("EmployeeIdForTransffering");
					this.OnEmployeeIdForTransfferingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeIdForRecieving", DbType="BigInt")]
		public System.Nullable<long> EmployeeIdForRecieving
		{
			get
			{
				return this._EmployeeIdForRecieving;
			}
			set
			{
				if ((this._EmployeeIdForRecieving != value))
				{
					this.OnEmployeeIdForRecievingChanging(value);
					this.SendPropertyChanging();
					this._EmployeeIdForRecieving = value;
					this.SendPropertyChanged("EmployeeIdForRecieving");
					this.OnEmployeeIdForRecievingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BookRequestDetail")]
	public partial class BookRequestDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _BookRequestDetailId;
		
		private System.Nullable<long> _BookRequestId;
		
		private System.Nullable<long> _BookId;
		
		private System.Nullable<long> _Quantity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBookRequestDetailIdChanging(long value);
    partial void OnBookRequestDetailIdChanged();
    partial void OnBookRequestIdChanging(System.Nullable<long> value);
    partial void OnBookRequestIdChanged();
    partial void OnBookIdChanging(System.Nullable<long> value);
    partial void OnBookIdChanged();
    partial void OnQuantityChanging(System.Nullable<long> value);
    partial void OnQuantityChanged();
    #endregion
		
		public BookRequestDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookRequestDetailId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long BookRequestDetailId
		{
			get
			{
				return this._BookRequestDetailId;
			}
			set
			{
				if ((this._BookRequestDetailId != value))
				{
					this.OnBookRequestDetailIdChanging(value);
					this.SendPropertyChanging();
					this._BookRequestDetailId = value;
					this.SendPropertyChanged("BookRequestDetailId");
					this.OnBookRequestDetailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookRequestId", DbType="BigInt")]
		public System.Nullable<long> BookRequestId
		{
			get
			{
				return this._BookRequestId;
			}
			set
			{
				if ((this._BookRequestId != value))
				{
					this.OnBookRequestIdChanging(value);
					this.SendPropertyChanging();
					this._BookRequestId = value;
					this.SendPropertyChanged("BookRequestId");
					this.OnBookRequestIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookId", DbType="BigInt")]
		public System.Nullable<long> BookId
		{
			get
			{
				return this._BookId;
			}
			set
			{
				if ((this._BookId != value))
				{
					this.OnBookIdChanging(value);
					this.SendPropertyChanging();
					this._BookId = value;
					this.SendPropertyChanged("BookId");
					this.OnBookIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="BigInt")]
		public System.Nullable<long> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Borrower")]
	public partial class Borrower : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _BorrowerId;
		
		private string _BorrowerName;
		
		private string _BorrowerNationalityId;
		
		private string _BorrowerCardIdPic1;
		
		private string _BorrowerCardIdPic2;
		
		private System.Nullable<bool> _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBorrowerIdChanging(long value);
    partial void OnBorrowerIdChanged();
    partial void OnBorrowerNameChanging(string value);
    partial void OnBorrowerNameChanged();
    partial void OnBorrowerNationalityIdChanging(string value);
    partial void OnBorrowerNationalityIdChanged();
    partial void OnBorrowerCardIdPic1Changing(string value);
    partial void OnBorrowerCardIdPic1Changed();
    partial void OnBorrowerCardIdPic2Changing(string value);
    partial void OnBorrowerCardIdPic2Changed();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    #endregion
		
		public Borrower()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BorrowerId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long BorrowerId
		{
			get
			{
				return this._BorrowerId;
			}
			set
			{
				if ((this._BorrowerId != value))
				{
					this.OnBorrowerIdChanging(value);
					this.SendPropertyChanging();
					this._BorrowerId = value;
					this.SendPropertyChanged("BorrowerId");
					this.OnBorrowerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BorrowerName", DbType="NVarChar(MAX)")]
		public string BorrowerName
		{
			get
			{
				return this._BorrowerName;
			}
			set
			{
				if ((this._BorrowerName != value))
				{
					this.OnBorrowerNameChanging(value);
					this.SendPropertyChanging();
					this._BorrowerName = value;
					this.SendPropertyChanged("BorrowerName");
					this.OnBorrowerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BorrowerNationalityId", DbType="NVarChar(MAX)")]
		public string BorrowerNationalityId
		{
			get
			{
				return this._BorrowerNationalityId;
			}
			set
			{
				if ((this._BorrowerNationalityId != value))
				{
					this.OnBorrowerNationalityIdChanging(value);
					this.SendPropertyChanging();
					this._BorrowerNationalityId = value;
					this.SendPropertyChanged("BorrowerNationalityId");
					this.OnBorrowerNationalityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BorrowerCardIdPic1", DbType="NVarChar(MAX)")]
		public string BorrowerCardIdPic1
		{
			get
			{
				return this._BorrowerCardIdPic1;
			}
			set
			{
				if ((this._BorrowerCardIdPic1 != value))
				{
					this.OnBorrowerCardIdPic1Changing(value);
					this.SendPropertyChanging();
					this._BorrowerCardIdPic1 = value;
					this.SendPropertyChanged("BorrowerCardIdPic1");
					this.OnBorrowerCardIdPic1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BorrowerCardIdPic2", DbType="NVarChar(MAX)")]
		public string BorrowerCardIdPic2
		{
			get
			{
				return this._BorrowerCardIdPic2;
			}
			set
			{
				if ((this._BorrowerCardIdPic2 != value))
				{
					this.OnBorrowerCardIdPic2Changing(value);
					this.SendPropertyChanging();
					this._BorrowerCardIdPic2 = value;
					this.SendPropertyChanged("BorrowerCardIdPic2");
					this.OnBorrowerCardIdPic2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BorrowerBook")]
	public partial class BorrowerBook : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _BorrowerBookId;
		
		private System.Nullable<long> _BorrowerId;
		
		private System.Nullable<long> _BookId;
		
		private System.Nullable<System.DateTime> _BorrowDate;
		
		private System.Nullable<System.DateTime> _BorrowReturnDate;
		
		private System.Nullable<bool> _IsReturned;
		
		private System.Nullable<long> _EmployeeIdForBorrow;
		
		private System.Nullable<long> _EmployeeIdForReturn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBorrowerBookIdChanging(long value);
    partial void OnBorrowerBookIdChanged();
    partial void OnBorrowerIdChanging(System.Nullable<long> value);
    partial void OnBorrowerIdChanged();
    partial void OnBookIdChanging(System.Nullable<long> value);
    partial void OnBookIdChanged();
    partial void OnBorrowDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBorrowDateChanged();
    partial void OnBorrowReturnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBorrowReturnDateChanged();
    partial void OnIsReturnedChanging(System.Nullable<bool> value);
    partial void OnIsReturnedChanged();
    partial void OnEmployeeIdForBorrowChanging(System.Nullable<long> value);
    partial void OnEmployeeIdForBorrowChanged();
    partial void OnEmployeeIdForReturnChanging(System.Nullable<long> value);
    partial void OnEmployeeIdForReturnChanged();
    #endregion
		
		public BorrowerBook()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BorrowerBookId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long BorrowerBookId
		{
			get
			{
				return this._BorrowerBookId;
			}
			set
			{
				if ((this._BorrowerBookId != value))
				{
					this.OnBorrowerBookIdChanging(value);
					this.SendPropertyChanging();
					this._BorrowerBookId = value;
					this.SendPropertyChanged("BorrowerBookId");
					this.OnBorrowerBookIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BorrowerId", DbType="BigInt")]
		public System.Nullable<long> BorrowerId
		{
			get
			{
				return this._BorrowerId;
			}
			set
			{
				if ((this._BorrowerId != value))
				{
					this.OnBorrowerIdChanging(value);
					this.SendPropertyChanging();
					this._BorrowerId = value;
					this.SendPropertyChanged("BorrowerId");
					this.OnBorrowerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookId", DbType="BigInt")]
		public System.Nullable<long> BookId
		{
			get
			{
				return this._BookId;
			}
			set
			{
				if ((this._BookId != value))
				{
					this.OnBookIdChanging(value);
					this.SendPropertyChanging();
					this._BookId = value;
					this.SendPropertyChanged("BookId");
					this.OnBookIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BorrowDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BorrowDate
		{
			get
			{
				return this._BorrowDate;
			}
			set
			{
				if ((this._BorrowDate != value))
				{
					this.OnBorrowDateChanging(value);
					this.SendPropertyChanging();
					this._BorrowDate = value;
					this.SendPropertyChanged("BorrowDate");
					this.OnBorrowDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BorrowReturnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BorrowReturnDate
		{
			get
			{
				return this._BorrowReturnDate;
			}
			set
			{
				if ((this._BorrowReturnDate != value))
				{
					this.OnBorrowReturnDateChanging(value);
					this.SendPropertyChanging();
					this._BorrowReturnDate = value;
					this.SendPropertyChanged("BorrowReturnDate");
					this.OnBorrowReturnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsReturned", DbType="Bit")]
		public System.Nullable<bool> IsReturned
		{
			get
			{
				return this._IsReturned;
			}
			set
			{
				if ((this._IsReturned != value))
				{
					this.OnIsReturnedChanging(value);
					this.SendPropertyChanging();
					this._IsReturned = value;
					this.SendPropertyChanged("IsReturned");
					this.OnIsReturnedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeIdForBorrow", DbType="BigInt")]
		public System.Nullable<long> EmployeeIdForBorrow
		{
			get
			{
				return this._EmployeeIdForBorrow;
			}
			set
			{
				if ((this._EmployeeIdForBorrow != value))
				{
					this.OnEmployeeIdForBorrowChanging(value);
					this.SendPropertyChanging();
					this._EmployeeIdForBorrow = value;
					this.SendPropertyChanged("EmployeeIdForBorrow");
					this.OnEmployeeIdForBorrowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeIdForReturn", DbType="BigInt")]
		public System.Nullable<long> EmployeeIdForReturn
		{
			get
			{
				return this._EmployeeIdForReturn;
			}
			set
			{
				if ((this._EmployeeIdForReturn != value))
				{
					this.OnEmployeeIdForReturnChanging(value);
					this.SendPropertyChanging();
					this._EmployeeIdForReturn = value;
					this.SendPropertyChanged("EmployeeIdForReturn");
					this.OnEmployeeIdForReturnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Category")]
	public partial class Category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _CategoryId;
		
		private string _CategoryName;
		
		private System.Nullable<bool> _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategoryIdChanging(long value);
    partial void OnCategoryIdChanged();
    partial void OnCategoryNameChanging(string value);
    partial void OnCategoryNameChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    #endregion
		
		public Category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this.OnCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._CategoryId = value;
					this.SendPropertyChanged("CategoryId");
					this.OnCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(MAX)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this.OnCategoryNameChanging(value);
					this.SendPropertyChanging();
					this._CategoryName = value;
					this.SendPropertyChanged("CategoryName");
					this.OnCategoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DocType")]
	public partial class DocType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _DocTypeId;
		
		private string _DocTypeDesc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDocTypeIdChanging(long value);
    partial void OnDocTypeIdChanged();
    partial void OnDocTypeDescChanging(string value);
    partial void OnDocTypeDescChanged();
    #endregion
		
		public DocType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocTypeId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long DocTypeId
		{
			get
			{
				return this._DocTypeId;
			}
			set
			{
				if ((this._DocTypeId != value))
				{
					this.OnDocTypeIdChanging(value);
					this.SendPropertyChanging();
					this._DocTypeId = value;
					this.SendPropertyChanged("DocTypeId");
					this.OnDocTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocTypeDesc", DbType="NVarChar(MAX)")]
		public string DocTypeDesc
		{
			get
			{
				return this._DocTypeDesc;
			}
			set
			{
				if ((this._DocTypeDesc != value))
				{
					this.OnDocTypeDescChanging(value);
					this.SendPropertyChanging();
					this._DocTypeDesc = value;
					this.SendPropertyChanged("DocTypeDesc");
					this.OnDocTypeDescChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _EmployeeId;
		
		private string _EmployeeName;
		
		private System.Nullable<System.DateTime> _EmployeeBirthDate;
		
		private System.Nullable<System.DateTime> _EmployeeHierDate;
		
		private System.Nullable<decimal> _EmployeeSalary;
		
		private System.Nullable<bool> _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmployeeIdChanging(long value);
    partial void OnEmployeeIdChanged();
    partial void OnEmployeeNameChanging(string value);
    partial void OnEmployeeNameChanged();
    partial void OnEmployeeBirthDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEmployeeBirthDateChanged();
    partial void OnEmployeeHierDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEmployeeHierDateChanged();
    partial void OnEmployeeSalaryChanging(System.Nullable<decimal> value);
    partial void OnEmployeeSalaryChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    #endregion
		
		public Employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					this.OnEmployeeIdChanging(value);
					this.SendPropertyChanging();
					this._EmployeeId = value;
					this.SendPropertyChanged("EmployeeId");
					this.OnEmployeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeName", DbType="NVarChar(MAX)")]
		public string EmployeeName
		{
			get
			{
				return this._EmployeeName;
			}
			set
			{
				if ((this._EmployeeName != value))
				{
					this.OnEmployeeNameChanging(value);
					this.SendPropertyChanging();
					this._EmployeeName = value;
					this.SendPropertyChanged("EmployeeName");
					this.OnEmployeeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeBirthDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EmployeeBirthDate
		{
			get
			{
				return this._EmployeeBirthDate;
			}
			set
			{
				if ((this._EmployeeBirthDate != value))
				{
					this.OnEmployeeBirthDateChanging(value);
					this.SendPropertyChanging();
					this._EmployeeBirthDate = value;
					this.SendPropertyChanged("EmployeeBirthDate");
					this.OnEmployeeBirthDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeHierDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EmployeeHierDate
		{
			get
			{
				return this._EmployeeHierDate;
			}
			set
			{
				if ((this._EmployeeHierDate != value))
				{
					this.OnEmployeeHierDateChanging(value);
					this.SendPropertyChanging();
					this._EmployeeHierDate = value;
					this.SendPropertyChanged("EmployeeHierDate");
					this.OnEmployeeHierDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeSalary", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> EmployeeSalary
		{
			get
			{
				return this._EmployeeSalary;
			}
			set
			{
				if ((this._EmployeeSalary != value))
				{
					this.OnEmployeeSalaryChanging(value);
					this.SendPropertyChanging();
					this._EmployeeSalary = value;
					this.SendPropertyChanged("EmployeeSalary");
					this.OnEmployeeSalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nationality")]
	public partial class Nationality : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _NationalityId;
		
		private string _NationalityDesc;
		
		private System.Nullable<bool> _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNationalityIdChanging(long value);
    partial void OnNationalityIdChanged();
    partial void OnNationalityDescChanging(string value);
    partial void OnNationalityDescChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    #endregion
		
		public Nationality()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalityId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long NationalityId
		{
			get
			{
				return this._NationalityId;
			}
			set
			{
				if ((this._NationalityId != value))
				{
					this.OnNationalityIdChanging(value);
					this.SendPropertyChanging();
					this._NationalityId = value;
					this.SendPropertyChanged("NationalityId");
					this.OnNationalityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalityDesc", DbType="NVarChar(MAX)")]
		public string NationalityDesc
		{
			get
			{
				return this._NationalityDesc;
			}
			set
			{
				if ((this._NationalityDesc != value))
				{
					this.OnNationalityDescChanging(value);
					this.SendPropertyChanging();
					this._NationalityDesc = value;
					this.SendPropertyChanged("NationalityDesc");
					this.OnNationalityDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Store")]
	public partial class Store : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _StoreId;
		
		private string _StoreDesc;
		
		private System.Nullable<bool> _StoreIsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStoreIdChanging(long value);
    partial void OnStoreIdChanged();
    partial void OnStoreDescChanging(string value);
    partial void OnStoreDescChanged();
    partial void OnStoreIsActiveChanging(System.Nullable<bool> value);
    partial void OnStoreIsActiveChanged();
    #endregion
		
		public Store()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long StoreId
		{
			get
			{
				return this._StoreId;
			}
			set
			{
				if ((this._StoreId != value))
				{
					this.OnStoreIdChanging(value);
					this.SendPropertyChanging();
					this._StoreId = value;
					this.SendPropertyChanged("StoreId");
					this.OnStoreIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreDesc", DbType="NVarChar(MAX)")]
		public string StoreDesc
		{
			get
			{
				return this._StoreDesc;
			}
			set
			{
				if ((this._StoreDesc != value))
				{
					this.OnStoreDescChanging(value);
					this.SendPropertyChanging();
					this._StoreDesc = value;
					this.SendPropertyChanged("StoreDesc");
					this.OnStoreDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreIsActive", DbType="Bit")]
		public System.Nullable<bool> StoreIsActive
		{
			get
			{
				return this._StoreIsActive;
			}
			set
			{
				if ((this._StoreIsActive != value))
				{
					this.OnStoreIsActiveChanging(value);
					this.SendPropertyChanging();
					this._StoreIsActive = value;
					this.SendPropertyChanged("StoreIsActive");
					this.OnStoreIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InvoiceMaster")]
	public partial class InvoiceMaster : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Invoice_Id;
		
		private System.Nullable<System.DateTime> _InvoiceDate;
		
		private System.Nullable<int> _BookId;
		
		private System.Nullable<int> _StoreId;
		
		private System.Nullable<decimal> _InvoiceNetValue;
		
		private System.Nullable<decimal> _InvoiceNetValueAfterDiscount;
		
		private System.Nullable<decimal> _InvoiceDiscount;
		
		private System.Nullable<decimal> _SubmittedValue;
		
		private System.Nullable<int> _tregary_ID;
		
		private System.Nullable<int> _EmployeeId;
		
		private System.Nullable<decimal> _MainDiscount;
		
		private System.Nullable<int> _SeasoneId;
		
		private System.Nullable<int> _DocTypeId;
		
		private System.Nullable<decimal> _LastFinalTotalDiscount;
		
		private System.Nullable<decimal> _FinalInvoiceWinValue;
		
		private System.Nullable<decimal> _InvoiceWinValue;
		
		private System.Nullable<decimal> _InvoiceNetValue2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInvoice_IdChanging(int value);
    partial void OnInvoice_IdChanged();
    partial void OnInvoiceDateChanging(System.Nullable<System.DateTime> value);
    partial void OnInvoiceDateChanged();
    partial void OnBookIdChanging(System.Nullable<int> value);
    partial void OnBookIdChanged();
    partial void OnStoreIdChanging(System.Nullable<int> value);
    partial void OnStoreIdChanged();
    partial void OnInvoiceNetValueChanging(System.Nullable<decimal> value);
    partial void OnInvoiceNetValueChanged();
    partial void OnInvoiceNetValueAfterDiscountChanging(System.Nullable<decimal> value);
    partial void OnInvoiceNetValueAfterDiscountChanged();
    partial void OnInvoiceDiscountChanging(System.Nullable<decimal> value);
    partial void OnInvoiceDiscountChanged();
    partial void OnSubmittedValueChanging(System.Nullable<decimal> value);
    partial void OnSubmittedValueChanged();
    partial void Ontregary_IDChanging(System.Nullable<int> value);
    partial void Ontregary_IDChanged();
    partial void OnEmployeeIdChanging(System.Nullable<int> value);
    partial void OnEmployeeIdChanged();
    partial void OnMainDiscountChanging(System.Nullable<decimal> value);
    partial void OnMainDiscountChanged();
    partial void OnSeasoneIdChanging(System.Nullable<int> value);
    partial void OnSeasoneIdChanged();
    partial void OnDocTypeIdChanging(System.Nullable<int> value);
    partial void OnDocTypeIdChanged();
    partial void OnLastFinalTotalDiscountChanging(System.Nullable<decimal> value);
    partial void OnLastFinalTotalDiscountChanged();
    partial void OnFinalInvoiceWinValueChanging(System.Nullable<decimal> value);
    partial void OnFinalInvoiceWinValueChanged();
    partial void OnInvoiceWinValueChanging(System.Nullable<decimal> value);
    partial void OnInvoiceWinValueChanged();
    partial void OnInvoiceNetValue2Changing(System.Nullable<decimal> value);
    partial void OnInvoiceNetValue2Changed();
    #endregion
		
		public InvoiceMaster()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Invoice Id]", Storage="_Invoice_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Invoice_Id
		{
			get
			{
				return this._Invoice_Id;
			}
			set
			{
				if ((this._Invoice_Id != value))
				{
					this.OnInvoice_IdChanging(value);
					this.SendPropertyChanging();
					this._Invoice_Id = value;
					this.SendPropertyChanged("Invoice_Id");
					this.OnInvoice_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> InvoiceDate
		{
			get
			{
				return this._InvoiceDate;
			}
			set
			{
				if ((this._InvoiceDate != value))
				{
					this.OnInvoiceDateChanging(value);
					this.SendPropertyChanging();
					this._InvoiceDate = value;
					this.SendPropertyChanged("InvoiceDate");
					this.OnInvoiceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookId", DbType="Int")]
		public System.Nullable<int> BookId
		{
			get
			{
				return this._BookId;
			}
			set
			{
				if ((this._BookId != value))
				{
					this.OnBookIdChanging(value);
					this.SendPropertyChanging();
					this._BookId = value;
					this.SendPropertyChanged("BookId");
					this.OnBookIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreId", DbType="Int")]
		public System.Nullable<int> StoreId
		{
			get
			{
				return this._StoreId;
			}
			set
			{
				if ((this._StoreId != value))
				{
					this.OnStoreIdChanging(value);
					this.SendPropertyChanging();
					this._StoreId = value;
					this.SendPropertyChanged("StoreId");
					this.OnStoreIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNetValue", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> InvoiceNetValue
		{
			get
			{
				return this._InvoiceNetValue;
			}
			set
			{
				if ((this._InvoiceNetValue != value))
				{
					this.OnInvoiceNetValueChanging(value);
					this.SendPropertyChanging();
					this._InvoiceNetValue = value;
					this.SendPropertyChanged("InvoiceNetValue");
					this.OnInvoiceNetValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNetValueAfterDiscount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> InvoiceNetValueAfterDiscount
		{
			get
			{
				return this._InvoiceNetValueAfterDiscount;
			}
			set
			{
				if ((this._InvoiceNetValueAfterDiscount != value))
				{
					this.OnInvoiceNetValueAfterDiscountChanging(value);
					this.SendPropertyChanging();
					this._InvoiceNetValueAfterDiscount = value;
					this.SendPropertyChanged("InvoiceNetValueAfterDiscount");
					this.OnInvoiceNetValueAfterDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDiscount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> InvoiceDiscount
		{
			get
			{
				return this._InvoiceDiscount;
			}
			set
			{
				if ((this._InvoiceDiscount != value))
				{
					this.OnInvoiceDiscountChanging(value);
					this.SendPropertyChanging();
					this._InvoiceDiscount = value;
					this.SendPropertyChanged("InvoiceDiscount");
					this.OnInvoiceDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittedValue", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SubmittedValue
		{
			get
			{
				return this._SubmittedValue;
			}
			set
			{
				if ((this._SubmittedValue != value))
				{
					this.OnSubmittedValueChanging(value);
					this.SendPropertyChanging();
					this._SubmittedValue = value;
					this.SendPropertyChanged("SubmittedValue");
					this.OnSubmittedValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tregary_ID", DbType="Int")]
		public System.Nullable<int> tregary_ID
		{
			get
			{
				return this._tregary_ID;
			}
			set
			{
				if ((this._tregary_ID != value))
				{
					this.Ontregary_IDChanging(value);
					this.SendPropertyChanging();
					this._tregary_ID = value;
					this.SendPropertyChanged("tregary_ID");
					this.Ontregary_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", DbType="Int")]
		public System.Nullable<int> EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					this.OnEmployeeIdChanging(value);
					this.SendPropertyChanging();
					this._EmployeeId = value;
					this.SendPropertyChanged("EmployeeId");
					this.OnEmployeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainDiscount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MainDiscount
		{
			get
			{
				return this._MainDiscount;
			}
			set
			{
				if ((this._MainDiscount != value))
				{
					this.OnMainDiscountChanging(value);
					this.SendPropertyChanging();
					this._MainDiscount = value;
					this.SendPropertyChanged("MainDiscount");
					this.OnMainDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeasoneId", DbType="Int")]
		public System.Nullable<int> SeasoneId
		{
			get
			{
				return this._SeasoneId;
			}
			set
			{
				if ((this._SeasoneId != value))
				{
					this.OnSeasoneIdChanging(value);
					this.SendPropertyChanging();
					this._SeasoneId = value;
					this.SendPropertyChanged("SeasoneId");
					this.OnSeasoneIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocTypeId", DbType="Int")]
		public System.Nullable<int> DocTypeId
		{
			get
			{
				return this._DocTypeId;
			}
			set
			{
				if ((this._DocTypeId != value))
				{
					this.OnDocTypeIdChanging(value);
					this.SendPropertyChanging();
					this._DocTypeId = value;
					this.SendPropertyChanged("DocTypeId");
					this.OnDocTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastFinalTotalDiscount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> LastFinalTotalDiscount
		{
			get
			{
				return this._LastFinalTotalDiscount;
			}
			set
			{
				if ((this._LastFinalTotalDiscount != value))
				{
					this.OnLastFinalTotalDiscountChanging(value);
					this.SendPropertyChanging();
					this._LastFinalTotalDiscount = value;
					this.SendPropertyChanged("LastFinalTotalDiscount");
					this.OnLastFinalTotalDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinalInvoiceWinValue", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> FinalInvoiceWinValue
		{
			get
			{
				return this._FinalInvoiceWinValue;
			}
			set
			{
				if ((this._FinalInvoiceWinValue != value))
				{
					this.OnFinalInvoiceWinValueChanging(value);
					this.SendPropertyChanging();
					this._FinalInvoiceWinValue = value;
					this.SendPropertyChanged("FinalInvoiceWinValue");
					this.OnFinalInvoiceWinValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceWinValue", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> InvoiceWinValue
		{
			get
			{
				return this._InvoiceWinValue;
			}
			set
			{
				if ((this._InvoiceWinValue != value))
				{
					this.OnInvoiceWinValueChanging(value);
					this.SendPropertyChanging();
					this._InvoiceWinValue = value;
					this.SendPropertyChanged("InvoiceWinValue");
					this.OnInvoiceWinValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNetValue2", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> InvoiceNetValue2
		{
			get
			{
				return this._InvoiceNetValue2;
			}
			set
			{
				if ((this._InvoiceNetValue2 != value))
				{
					this.OnInvoiceNetValue2Changing(value);
					this.SendPropertyChanging();
					this._InvoiceNetValue2 = value;
					this.SendPropertyChanged("InvoiceNetValue2");
					this.OnInvoiceNetValue2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InvoiceMasterDetail")]
	public partial class InvoiceMasterDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _InvoiceDetailId;
		
		private System.Nullable<decimal> _BookPrice;
		
		private System.Nullable<int> _BookId;
		
		private System.Nullable<decimal> _Quantity;
		
		private System.Nullable<decimal> _Total;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInvoiceDetailIdChanging(int value);
    partial void OnInvoiceDetailIdChanged();
    partial void OnBookPriceChanging(System.Nullable<decimal> value);
    partial void OnBookPriceChanged();
    partial void OnBookIdChanging(System.Nullable<int> value);
    partial void OnBookIdChanged();
    partial void OnQuantityChanging(System.Nullable<decimal> value);
    partial void OnQuantityChanged();
    partial void OnTotalChanging(System.Nullable<decimal> value);
    partial void OnTotalChanged();
    #endregion
		
		public InvoiceMasterDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDetailId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int InvoiceDetailId
		{
			get
			{
				return this._InvoiceDetailId;
			}
			set
			{
				if ((this._InvoiceDetailId != value))
				{
					this.OnInvoiceDetailIdChanging(value);
					this.SendPropertyChanging();
					this._InvoiceDetailId = value;
					this.SendPropertyChanged("InvoiceDetailId");
					this.OnInvoiceDetailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookPrice", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> BookPrice
		{
			get
			{
				return this._BookPrice;
			}
			set
			{
				if ((this._BookPrice != value))
				{
					this.OnBookPriceChanging(value);
					this.SendPropertyChanging();
					this._BookPrice = value;
					this.SendPropertyChanged("BookPrice");
					this.OnBookPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookId", DbType="Int")]
		public System.Nullable<int> BookId
		{
			get
			{
				return this._BookId;
			}
			set
			{
				if ((this._BookId != value))
				{
					this.OnBookIdChanging(value);
					this.SendPropertyChanging();
					this._BookId = value;
					this.SendPropertyChanged("BookId");
					this.OnBookIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BookStore")]
	public partial class BookStore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _BookStoreId;
		
		private System.Nullable<long> _StoreId;
		
		private System.Nullable<long> _BookId;
		
		private System.Nullable<long> _QuantityOnHand;
		
		private System.Nullable<decimal> _Bookllpirice;
		
		private System.Nullable<decimal> _Bookbuypirice;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBookStoreIdChanging(long value);
    partial void OnBookStoreIdChanged();
    partial void OnStoreIdChanging(System.Nullable<long> value);
    partial void OnStoreIdChanged();
    partial void OnBookIdChanging(System.Nullable<long> value);
    partial void OnBookIdChanged();
    partial void OnQuantityOnHandChanging(System.Nullable<long> value);
    partial void OnQuantityOnHandChanged();
    partial void OnBookllpiriceChanging(System.Nullable<decimal> value);
    partial void OnBookllpiriceChanged();
    partial void OnBookbuypiriceChanging(System.Nullable<decimal> value);
    partial void OnBookbuypiriceChanged();
    #endregion
		
		public BookStore()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookStoreId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long BookStoreId
		{
			get
			{
				return this._BookStoreId;
			}
			set
			{
				if ((this._BookStoreId != value))
				{
					this.OnBookStoreIdChanging(value);
					this.SendPropertyChanging();
					this._BookStoreId = value;
					this.SendPropertyChanged("BookStoreId");
					this.OnBookStoreIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreId", DbType="BigInt")]
		public System.Nullable<long> StoreId
		{
			get
			{
				return this._StoreId;
			}
			set
			{
				if ((this._StoreId != value))
				{
					this.OnStoreIdChanging(value);
					this.SendPropertyChanging();
					this._StoreId = value;
					this.SendPropertyChanged("StoreId");
					this.OnStoreIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookId", DbType="BigInt")]
		public System.Nullable<long> BookId
		{
			get
			{
				return this._BookId;
			}
			set
			{
				if ((this._BookId != value))
				{
					this.OnBookIdChanging(value);
					this.SendPropertyChanging();
					this._BookId = value;
					this.SendPropertyChanged("BookId");
					this.OnBookIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuantityOnHand", DbType="BigInt")]
		public System.Nullable<long> QuantityOnHand
		{
			get
			{
				return this._QuantityOnHand;
			}
			set
			{
				if ((this._QuantityOnHand != value))
				{
					this.OnQuantityOnHandChanging(value);
					this.SendPropertyChanging();
					this._QuantityOnHand = value;
					this.SendPropertyChanged("QuantityOnHand");
					this.OnQuantityOnHandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bookllpirice", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Bookllpirice
		{
			get
			{
				return this._Bookllpirice;
			}
			set
			{
				if ((this._Bookllpirice != value))
				{
					this.OnBookllpiriceChanging(value);
					this.SendPropertyChanging();
					this._Bookllpirice = value;
					this.SendPropertyChanged("Bookllpirice");
					this.OnBookllpiriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bookbuypirice", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Bookbuypirice
		{
			get
			{
				return this._Bookbuypirice;
			}
			set
			{
				if ((this._Bookbuypirice != value))
				{
					this.OnBookbuypiriceChanging(value);
					this.SendPropertyChanging();
					this._Bookbuypirice = value;
					this.SendPropertyChanged("Bookbuypirice");
					this.OnBookbuypiriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Book")]
	public partial class Book : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _BookId;
		
		private string _BookName;
		
		private System.Nullable<long> _CategoryId;
		
		private System.Nullable<long> _AuthorId;
		
		private System.Nullable<System.DateTime> _DateOfPublication;
		
		private System.Nullable<int> _BeginingBalance;
		
		private System.Nullable<bool> _IsActive;
		
		private string _BookBarcode;
		
		private System.Nullable<decimal> _Bookbuypirice;
		
		private string _Bookllpirice;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBookIdChanging(long value);
    partial void OnBookIdChanged();
    partial void OnBookNameChanging(string value);
    partial void OnBookNameChanged();
    partial void OnCategoryIdChanging(System.Nullable<long> value);
    partial void OnCategoryIdChanged();
    partial void OnAuthorIdChanging(System.Nullable<long> value);
    partial void OnAuthorIdChanged();
    partial void OnDateOfPublicationChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfPublicationChanged();
    partial void OnBeginingBalanceChanging(System.Nullable<int> value);
    partial void OnBeginingBalanceChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    partial void OnBookBarcodeChanging(string value);
    partial void OnBookBarcodeChanged();
    partial void OnBookbuypiriceChanging(System.Nullable<decimal> value);
    partial void OnBookbuypiriceChanged();
    partial void OnBookllpiriceChanging(string value);
    partial void OnBookllpiriceChanged();
    #endregion
		
		public Book()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long BookId
		{
			get
			{
				return this._BookId;
			}
			set
			{
				if ((this._BookId != value))
				{
					this.OnBookIdChanging(value);
					this.SendPropertyChanging();
					this._BookId = value;
					this.SendPropertyChanged("BookId");
					this.OnBookIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookName", DbType="NVarChar(MAX)")]
		public string BookName
		{
			get
			{
				return this._BookName;
			}
			set
			{
				if ((this._BookName != value))
				{
					this.OnBookNameChanging(value);
					this.SendPropertyChanging();
					this._BookName = value;
					this.SendPropertyChanged("BookName");
					this.OnBookNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", DbType="BigInt")]
		public System.Nullable<long> CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this.OnCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._CategoryId = value;
					this.SendPropertyChanged("CategoryId");
					this.OnCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorId", DbType="BigInt")]
		public System.Nullable<long> AuthorId
		{
			get
			{
				return this._AuthorId;
			}
			set
			{
				if ((this._AuthorId != value))
				{
					this.OnAuthorIdChanging(value);
					this.SendPropertyChanging();
					this._AuthorId = value;
					this.SendPropertyChanged("AuthorId");
					this.OnAuthorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfPublication", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateOfPublication
		{
			get
			{
				return this._DateOfPublication;
			}
			set
			{
				if ((this._DateOfPublication != value))
				{
					this.OnDateOfPublicationChanging(value);
					this.SendPropertyChanging();
					this._DateOfPublication = value;
					this.SendPropertyChanged("DateOfPublication");
					this.OnDateOfPublicationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginingBalance", DbType="Int")]
		public System.Nullable<int> BeginingBalance
		{
			get
			{
				return this._BeginingBalance;
			}
			set
			{
				if ((this._BeginingBalance != value))
				{
					this.OnBeginingBalanceChanging(value);
					this.SendPropertyChanging();
					this._BeginingBalance = value;
					this.SendPropertyChanged("BeginingBalance");
					this.OnBeginingBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookBarcode", DbType="NVarChar(MAX)")]
		public string BookBarcode
		{
			get
			{
				return this._BookBarcode;
			}
			set
			{
				if ((this._BookBarcode != value))
				{
					this.OnBookBarcodeChanging(value);
					this.SendPropertyChanging();
					this._BookBarcode = value;
					this.SendPropertyChanged("BookBarcode");
					this.OnBookBarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bookbuypirice", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Bookbuypirice
		{
			get
			{
				return this._Bookbuypirice;
			}
			set
			{
				if ((this._Bookbuypirice != value))
				{
					this.OnBookbuypiriceChanging(value);
					this.SendPropertyChanging();
					this._Bookbuypirice = value;
					this.SendPropertyChanged("Bookbuypirice");
					this.OnBookbuypiriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bookllpirice", DbType="NChar(10)")]
		public string Bookllpirice
		{
			get
			{
				return this._Bookllpirice;
			}
			set
			{
				if ((this._Bookllpirice != value))
				{
					this.OnBookllpiriceChanging(value);
					this.SendPropertyChanging();
					this._Bookllpirice = value;
					this.SendPropertyChanged("Bookllpirice");
					this.OnBookllpiriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
